const IDLE_ALERT_RECIPIENT = "girivasan@infowaygroup.com";
const IDLE_ALERT_THRESHOLD_MINUTES = Number(
  process.env.IDLE_ALERT_THRESHOLD_MINUTES || 5
);
const IDLE_ALERT_SCHEDULER_INTERVAL_MS = Number(
  process.env.IDLE_ALERT_SCHEDULER_INTERVAL_MS || 60_000
);
const HEARTBEAT_STALE_AFTER_SECONDS = 30;

if (!Number.isFinite(IDLE_ALERT_THRESHOLD_MINUTES) || IDLE_ALERT_THRESHOLD_MINUTES <= 0) {
  throw new Error("IDLE_ALERT_THRESHOLD_MINUTES must be a positive number");
}

module.exports = {
  HEARTBEAT_STALE_AFTER_SECONDS,
  IDLE_ALERT_RECIPIENT,
  IDLE_ALERT_SCHEDULER_INTERVAL_MS,
  IDLE_ALERT_THRESHOLD_MINUTES,
  IDLE_ALERT_THRESHOLD_MS: IDLE_ALERT_THRESHOLD_MINUTES * 60 * 1000,
};
